### ISSUE TITLE
Can't reset selectedItem when re-logging in 

### ISSUE THREAD

**Issue by Linoman** [rhanbIT/nativescript-bottombar#14]
node v6.9.0
tns 3.0.1
nativescript-bottombar@3.0.5

Ok I have setup the bottom bar without much problem and it works as expected. Except with the current flow.

1. Start at LOGIN page, bottombar is not displayed, use login credentials
2. At HOME page, bottombar is displayed, HOME is highlighted (being the first entry)
3. Tap LOGUT at bottombar (3rd entry) and get back to LOGIN page.
4. Back at LOGIN page, bottombar is not displayed. Use login credentials again
5. At HOME page, bottombar is displayed, LOGOUT is highlighted

As additional info tapping HOME while logout triggers tabSelected, but does't refresh the page. Using this._bar.selectItem(0); when pressing LOGOUT does nothing.

**Comment by rhanbIT** [comment]
Hi @Linoman  and @anuragd7 ,

Could you provide a sample code please? 

`this._bar.selectItem(0); // should work`

Thanks

**Comment by Linoman** [comment]
This component is added in app.modult.ts under declarations

`
import { Component, OnInit } from "angular/core";
import { registerElement } from "nativescript-angular";
import { RouterExtensions } from "nativescript-angular/router";
import { BottomBar, BottomBarItem, TITLE_STATE, SelectedIndexChangedEventData, Notification } from "nativescript-bottombar";

import { AuthenticationService } from "../../../service";

const { debug } = require("../../../../app/config/environment.json");

registerElement('BottomBar', () => BottomBar);

@Component({
    moduleId: module.id,
    selector: 'bottom-sidebar-module',
    templateUrl: './bottom-sidebar.module.html',
    styleUrls: ['./bottom-sidebar.module.css']
})
export class BottomSidebarModule implements OnInit {

    public hidden: boolean;
    public titleState: TITLE_STATE;
    public _bar: BottomBar;
    public inactiveColor: string;
    public accentColor: string;

    public items: Array<BottomBarItem> = [
        new BottomBarItem(1, "Logout", "icon", "green")
    ];

    constructor(private authenticationService: AuthenticationService,
                private routerExtensions: RouterExtensions) {}

    ngOnInit(): void {}

    tabLoaded(event) {
        this._bar = <BottomBar>event.object;
        this.hidden = false;
        this.titleState = TITLE_STATE.SHOW_WHEN_ACTIVE;
        this.inactiveColor = "white";
        this.accentColor = "blue";
    }

    tabSelected(data: SelectedIndexChangedEventData) {
        // only triggered when a different tab is tapped
        if(debug) {
            console.log(`selectedTab ${data.newIndex}`);
        }
        switch (data.newIndex) {
            case 1:
                this.logout();
                break;
            case 0:
            default:
                this.goHome();
                break;
        }
    }

    private goHome(): void {
        this.routerExtensions.navigate(['/home']);
    }

    private logout(): void {
        this._bar.selectItem(0);
        this.authenticationService.logout();
        this.routerExtensions.navigate(['/login'], { clearHistory: true });
    }
}`

**Comment by rhanbIT** [comment]
Hi @Linoman 

Why do you have only one `BottomBarItem`? 

And your function `logout()` is called to change your router state which means that when you go back to the component a new BottomBar will be created so it's normal that selecting an item before changing of component doesn't do anything.

**Comment by Linoman** [comment]
Sorry I made a mistake and delete all code that's not relevant

**Comment by rhanbIT** [comment]
I don't manage to reproduce the issue, `selectItem()` function works for me.

**Comment by Linoman** [comment]
My HOME does work as expected (I had more items in the sample code) and I use the same routerExtensions.navigation as in logout. Does your example uses the bottomnav in the app.component?

**Comment by rhanbIT** [comment]
could you provide a repo pointing to your project? I don"t understand the context and how to reproduce the error. Thank you

**Comment by Linoman** [comment]
I'll make a small project reproducing the error. Give me a couple of hours

**Comment by anuragd7** [comment]
Hi @rhanbIT 
Please see this repo  for a sample of my issue
https://github.com/anuragd7/bottomBarExample/tree/master/app

My issue is that I am not able to set the active tab when navigating back to the first taab. In the function setActiveTabFromUrlChange i try to use selectItem()  on the bottombar but it is not found..

Thanks

**Comment by kmuthukrishnan** [comment]
Hi @rhanbIT,

I am facing a similar issue where I am not able to set the active tab. Pls help!

**Comment by rhanbIT** [comment]
Hi anuragd7,

I managed to fix the issue for `2.x support`, I implemented the `selectItem`method only for `3.0`that's why it wasn't working. 

Here are the steps to update the package:
- `tns plugin remove nativescript-bottombar`
- `tns plugin add nativescript-bottombar@2.1.4`

@Linoman and @kmuthukrishnan , please provide a sample code or a repository. 
I can't reproduce the issue on the latest `3.x`version.

**Comment by anuragd7** [comment]
Hi @rhanbIT 
Thanks for implementing the selectItem method, I tested it in my project. While the bottombar seems to work fine on IOS, however on android I am still getting an error. I have update the project so that you can see the error.  (https://github.com/anuragd7/bottomBarExample/tree/master/app)
 To see the error please
1.  Run the app - tns run android
2. Tap on Goto Other button
3. Then Tap Goto Test or Goto Test1 

On IOS this works fine but on android I get an error 

An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onCreateView failed

Error: Must have titleState
File: "file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/common.js, line: 140, column: 12

StackTrace: 
	Frame: function:'BottomBarCommon._titleStatePropertyChangedSetNativeValue', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/common.js', line: 140, column: 19
	Frame: function:'BottomBar._titleStatePropertyChangedSetNativeValue', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/android/bottombar.js', line: 212, column: 67
	Frame: function:'titleStateProperty.metadata.onSetNativeValue', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/common.js', line: 58, column: 15
	Frame: function:'ProxyObject._trySetNativeValue', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/proxy.js', line: 83, column: 27
	Frame: function:'eachPropertyCallback', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/proxy.js', line: 59, column: 18
	Frame: function:'DependencyObservable._eachSetProperty', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/dependency-observable.js', line: 241, column: 18
	Frame: function:'ProxyObject._syncNativeProperties', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/proxy.js', line: 62, column: 14
	Frame: function:'View._syncNativeProperties', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/view-common.js', line: 1230, column: 48
	Frame: function:'eachChild', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 162, column: 23
	Frame: function:'LayoutBase._eachChildView', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 144, column: 22
	Frame: function:'View._onAttached', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 165, column: 18
	Frame: function:'eachChild', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 158, column: 23
	Frame: function:'LayoutBase._eachChildView', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 144, column: 22
	Frame: function:'View._onAttached', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 165, column: 18
	Frame: function:'eachChild', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 158, column: 23
	Frame: function:'ContentView._eachChildView', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 65, column: 13
	Frame: function:'Page._eachChildView', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 285, column: 41
	Frame: function:'View._onAttached', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 165, column: 18
	Frame: function:'View._addViewCore', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 126, column: 18
	Frame: function:'View._addView', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/view-common.js', line: 1163, column: 14
	Frame: function:'onFragmentShown', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 40, column: 11
	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 612, column: 13
	Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 23, column: 38

**Comment by rhanbIT** [comment]
Hi,

Just move your initialisations in your constructor  instead of the `tabLoaded`callbcak like this:

``` typescript
constructor(private router: Router) {
        this.hidden = false;
        this.titleState = TITLE_STATE.SHOW_WHEN_ACTIVE;
        this.inactiveColor = "white";
        this.accentColor = "blue";
}
```

**Comment by anuragd7** [comment]
Hi @rhanbIT 
I moved the initialisation to the constructor. Now everything works fine on android but I observe the following on IOS
1. On tns run ios the text does not show under the initially selected tab.
2. When I navigate away from the initially selected tab and then return to it, the selected colour shows correctly but the text below the picture does not display correctly. 
I have updated the shared repo and you can see this behavior on ios by running that project.
Please look into this.
